export const COUNTRYINFO =[
  {
    "Country": "Angola",
    "ISO": "AGO",
    "ID": 1,
    "Upop": 15862758,
    "Upop_Scaled": 0.302,
    "Ulvl_Scaled": 0.63,
    "NumAgglos": 96,
    "NumAgglos_Scaled": 0.083,
    "Mpop": 0.747,
    "ADBC": 35.1,
    "ADBC_Scaled": 0.171,
    "Usurf": 0.0019,
    "Country_FR": "Angola",
    "name": "Luanda",
    "Tpop": 25178981,
    "X2": "Capital: Luanda",
    "Surface": "Population: 24 993 000",
    "description": "Angola is the fourth most urbanized country in Africa with 63.5% of the population living in urban areas in 2015 compared to less than half (30.5%) in 1990. The capital Luanda alone counts more than a quarter of the total population and dominates the urban landscape. Angola’s capital is almost 12 times as large as the second biggest city Lubango and it covers an area roughly 8 times as large. It has the second highest primacy index in all of Africa. The rapid growth of Luanda is in part due to the devastating civil war that ravaged the interior of the country from 1975 to 1992 and has made Luanda a refuge for many Angolans.\nDespite only having 25 million inhabitants in total, Angola counts 5 more agglomerations with more than 500 000 inhabitants: Lubango, Huambo, Cabinda, Benguela and Lobito.  The latter two are separated by less than 30km and are expected to merge into one big agglomeration in the next few years, bringing their total population to 1.6 million. The urban population density level is the fourth highest in Africa at an average of 6 767 inhabitants per km2. There are 7 233 inhabitants per km2 in Luanda but some cities such as Saurimo count more than 10 000 inhabitants per km2.\nThere are also 31 agglomerations with populations between 50 000 and 500 000 but very few smaller agglomerations with fewer than 50 000 inhabitants. Only 5.3% of Angolans live in smaller urban agglomerations. Given the size of the country, it is noticeable that the territory is only weakly inter-linked by urban agglomerations. Nonetheless, the road network between the agglomerations is quite well developed."
  },
  {
    "Country": "Burundi",
    "ISO": "BDI",
    "ID": 2,
    "Upop": 2054027,
    "Upop_Scaled": 0.184,
    "Ulvl_Scaled": 0.21,
    "NumAgglos": 33,
    "NumAgglos_Scaled": 0.028,
    "Mpop": 0.508,
    "ADBC": 39.4,
    "ADBC_Scaled": 0.191,
    "Usurf": 0.0213,
    "Country_FR": "Burundi",
    "name": "Bujumbura",
    "Tpop": 9781081,
    "X2": "Capital: Bujumbura",
    "Surface": "Population: 9 824 000",
    "description": "Officially, Burundi counts 26 cities of which 16 have a population between 2 000 to 10 000 inhabitants. This would give the country a level of urbanisation of just 10% compared to 20% according to the Geopolis methodology, which uses the built environment as a key indicator of urbanisation. Nonetheless, Burundi remains one of the least urbanised countries in the world.\nThe first urban agglomeration of more than 10 000 inhabitants only emerged in the 1940s. Until 2000, Burundi had the lowest level of urbanization in the world alongside Bhutan and Rwanda. At the time, the country only counted 6 urban agglomerations with more than 10 000 inhabitants and a level of urbanization of just 6.9%. Fifteen years later, these figures had jumped to 33 agglomerations and a level of urbanization of 20.9%. This sudden hike in numbers however, has less to do with population growth than with the spill-over of the agglomerations. Nonetheless, Burundi retains a distinctly non-urban character partially due to the topography of the country, which is dominated by numerous undulating hills creating a sprawling but interspersed periphery.\nBurundi’s primacy index is the third highest in Africa. The capital Bujumbura, which counted a population of just over 1 million in 2015, represents the largest agglomeration by far. The remaining 32 urban agglomerations have populations of fewer than 100 000. The relatively small size of the country however means that overall population density is quite high at 353 inhabitants per km2 (the second highest in Africa) and most of the urban agglomerations are dotted along the country’s territory in a fairly dense network."
  },
  {
    "Country": "Benin",
    "ISO": "BEN",
    "ID": 3,
    "Upop": 5072168,
    "Upop_Scaled": 0.21,
    "Ulvl_Scaled": 0.47,
    "NumAgglos": 111,
    "NumAgglos_Scaled": 0.096,
    "Mpop": 0.514,
    "ADBC": 54,
    "ADBC_Scaled": 0.262,
    "Usurf": 0.0102,
    "Country_FR": "Bénin",
    "name": "Porto Novo",
    "Tpop": 10791847,
    "X2": "Capital: Porto Novo",
    "Surface": "Population: 10 749 000",
    "description": "In 2015, almost half of the population of Benin lived in an urban agglomeration. Between 2000 and 2015, the country has seen a rapid increase in the total urban population, which has gone from 2.1 million to 5.1 million. Over the same period, the number of agglomerations has increased from 41 to 111, resulting from the rise of smaller agglomerations with fewer than 50 000 inhabitants.\nThe two largest urban agglomerations, Cotonou and Porto Novo, account for almost one fifth of the total population of the country. Both agglomerations are separated only by a few hundred meters of unbuilt land and are likely to merge into a bigger conurbation in a few years. By adding the multiple smaller and medium-sized agglomerations that are located around the Cotonou-Porto Novo agglomerations, a large metropolitan area emerges that holds almost half of the total population but only covers 10% of the surface area of Benin. The relative concentration of urban agglomerations in the country’s South is also reflected in the average distance between agglomerations, which is only 7.4 km in the metropolitan area but 22.6 km in the more sparsely populated North.\nThe only other larger agglomerations are Parakou in the North and Abomey-Bohicon. Both agglomerations have around 260 000 inhabitants. The remaining agglomerations have fewer than 83 000 inhabitants, which explains the relatively low weight of medium-sized cities in the urban population distribution. In fact, larger agglomerations of more than 500 000 and smaller ones with fewer than 50 000 inhabitants together account for 80% of the total urban population."
  },
  {
    "Country": "Burkina Faso",
    "ISO": "BFA",
    "ID": 4,
    "Upop": 5269493,
    "Upop_Scaled": 0.212,
    "Ulvl_Scaled": 0.29,
    "NumAgglos": 101,
    "NumAgglos_Scaled": 0.087,
    "Mpop": 0.563,
    "ADBC": 35,
    "ADBC_Scaled": 0.17,
    "Usurf": 0.0043,
    "Country_FR": "Burkina Faso",
    "name": "Ouagadougou",
    "Tpop": 18170666,
    "X2": "Capital: Ouagadougou",
    "Surface": "Population: 18 450 000",
    "description": "In 2015, only 28.6% of the population of Burkina Faso lived in urban agglomerations, making it the second least urbanised country in West Africa, behind Niger. The country counts a total of 101 urban agglomerations with a population of more than 10 000 but the distribution of the urban population is largely concentrated on two cities, Ouagadougou and Bobo-Dioulasso, which account for 56% of the total urban population in the country.\nThe primacy of the capital is limited by the former capital Bobo-Dioulasso whose population outstripped that of Ouagadougou by 10% in 1950 before the capital’s population growth reversed the trend 10 years later. Although Ouagadougou counted a population of 2.3 million in 2015 against 668 000 for Bobo-Dioulasso, the former capital still represents an important part of the urban population and is 6 times larger than the third biggest agglomeration Koudougou (pop. 111 000).\nAn interesting characteristic of Burkina Faso’s primary urban agglomerations is their location along the historic railroad connecting Abidjan (Ivory Coast) to Ouagadougou. The four biggest cities of the country are all located along this stretch. However, newer agglomerations are emerging elsewhere and often coincide with being the regional capitals (“chefs-lieux”) of the various départements. Burkina Faso has in fact seen many smaller agglomerations emerge over the past 20 years, going from 53 urban agglomerations in 2000 to 101 in 2015.\nThese smaller agglomerations often benefit from having a proper administration and the basic services associated with their status as regional capitals. As a result, they have a largely urban character, despite a relatively modest average urban density of 4 425 inhabitants per km2."
  },
  {
    "Country": "Botswana",
    "ISO": "BWA",
    "ID": 5,
    "Upop": 1224313,
    "Upop_Scaled": 0.177,
    "Ulvl_Scaled": 0.56,
    "NumAgglos": 25,
    "NumAgglos_Scaled": 0.022,
    "Mpop": 0.298,
    "ADBC": 30.1,
    "ADBC_Scaled": 0.146,
    "Usurf": 0.0013,
    "Country_FR": "Botswana",
    "name": "Gaborone",
    "Tpop": 2186273,
    "X2": "Capital: Gaborone",
    "Surface": "Population: 2 195 000",
    "description": "Botswana has is the second least densely populated country in Africa after Namibia with just 4 inhabitants per km2 (the same as Mauritania and Libya). It is at the same time, one of the most urbanized of the continent and has the second highest level of urbanization in Southern Africa at 55.8%. The level of urbanization has increased quite rapidly between 1970 and 2000, when it rose from 13.5% to 48.8% but has since slowed down, partially because of the decline in population growth which has continued until 2015.\nThe capital Gaborone accounts for almost a third of the total urban population. It is around three-and-a-half times larger than the second biggest agglomeration of Francistown. However, many of the other agglomerations are situated within a radius of 75 kilometers of the capital and together they represent 57% of the urban population. Most of the remaining agglomerations are situated to the North-East of Gaborone towards the borders with South Africa and Zambia. Overall, the country counts 25 urban agglomerations with populations of more than 10 000 inhabitants.\nBotswana’s urban agglomerations are characterized by their relative expanse and the generous allotments, which explain the relatively low urban population density of just 1 607 inhabitants per km2, the third lowest in Africa."
  },
  {
    "Country": "Central African Republic",
    "ISO": "CAF",
    "ID": 6,
    "Upop": 1832706,
    "Upop_Scaled": 0.182,
    "Ulvl_Scaled": 0.37,
    "NumAgglos": 31,
    "NumAgglos_Scaled": 0.027,
    "Mpop": 0.516,
    "ADBC": 31.6,
    "ADBC_Scaled": 0.154,
    "Usurf": 0.0004,
    "Country_FR": "République centrafricaine",
    "name": "Bangui",
    "Tpop": 4953259,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Ivory Coast",
    "ISO": "CIV",
    "ID": 7,
    "Upop": 11489818,
    "Upop_Scaled": 0.265,
    "Ulvl_Scaled": 0.49,
    "NumAgglos": 220,
    "NumAgglos_Scaled": 0.19,
    "Mpop": 0.503,
    "ADBC": 22.9,
    "ADBC_Scaled": 0.111,
    "Usurf": 0.0046,
    "Country_FR": "Côte d’Ivoire",
    "name": "Yamoussoukro",
    "Tpop": 23448608,
    "X2": "Capital: Yamoussoukro",
    "Surface": "Population: 23 300 000",
    "description": "In 2015, half of the population of Ivory Coast lived in urban agglomerations and 41% of urban dwellers lived in Abidjan. Abidjan is almost 9 times larger than the second biggest agglomeration Bouaké and more than 20 times larger than the capital Yamoussoukro. Its primacy has steadily grown and is expected to continue to increase.\nIvory Coast has the fastest growing population in West Africa. It has grown 11-fold since 1950 to reach 23.3 million in 2015. However, urbanization is a more recent phenomenon as most of the emerging agglomerations have only started to appear after the 1990, creating a very dense network of small agglomerations across the territory.\nUrbanization in Ivory Coast is marked by the relative weight of small agglomerations with populations between 10 000 and 50 000 inhabitants, which account for about 90% of all urban agglomerations and almost a third of all urban dwellers. By contrast, out of a total of 220 urban agglomerations captured by Africapolis, there were only 9 urban agglomerations with populations larger than 100 000.\nMany of the smaller agglomerations however, lack a distinctly urban character, including urban infrastructure, despite the high population density. In fact, Ivory Coast has the highest average urban population density in Sub-Saharan Africa with 7 769 inhabitants per km2. In Abidjan, the density is even higher at an average of 12 054 inhabitants per km2."
  },
  {
    "Country": "Cameroon",
    "ISO": "CMR",
    "ID": 8,
    "Upop": 12754444,
    "Upop_Scaled": 0.275,
    "Ulvl_Scaled": 0.55,
    "NumAgglos": 147,
    "NumAgglos_Scaled": 0.127,
    "Mpop": 0.646,
    "ADBC": 50.4,
    "ADBC_Scaled": 0.245,
    "Usurf": 0.0088,
    "Country_FR": "Cameroun",
    "name": "Yaounde",
    "Tpop": 23189898,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Congo",
    "ISO": "COG",
    "ID": 9,
    "Upop": 3108083,
    "Upop_Scaled": 0.193,
    "Ulvl_Scaled": 0.66,
    "NumAgglos": 27,
    "NumAgglos_Scaled": 0.023,
    "Mpop": 0.783,
    "ADBC": 16.2,
    "ADBC_Scaled": 0.079,
    "Usurf": 0.0017,
    "Country_FR": "Congo",
    "name": "Brazzaville",
    "Tpop": 4709217,
    "X2": "Capital: Brazzaville",
    "Surface": "Population: 4 688 000",
    "description": "Congo scores the second highest level of urbanization in Sub-Saharan Africa with two-thirds of its population living in urban agglomerations, despite a relatively low overall population size of only 4.7 million. Compared to other African states, the level of urbanization had already attained a significant level by 1970, when one third of the population lived in urban agglomerations.\nAlmost 80% of the urban population (equivalent to 2.4 million people) live in the two biggest agglomerations Brazzaville and Pointe Noire, located at both ends of the railway line connecting the Congo to the Atlantic Ocean. A further five agglomerations (Dolisie, Nkayi, Madingou, Loutélé and Bouansa) are located along the same stretch. Brazzaville itself is positioned across from the Democratic Republic of Congo’s capital Kinshasa and together they form one of the biggest urban settlements in Africa.\nDespite the modest weight of medium and small urban agglomerations in the total share of the urban population, many agglomerations with populations between 10 000 and 200 000 have emerged since 2000. Whilst there were only 15 urban agglomerations in this category in 2000, the number has risen to 25 by 2015."
  },
  {
    "Country": "Cabo Verde",
    "ISO": "CPV",
    "ID": 10,
    "Upop": 263913,
    "Upop_Scaled": 0.169,
    "Ulvl_Scaled": 0.5,
    "NumAgglos": 4,
    "NumAgglos_Scaled": 0.003,
    "Mpop": 0,
    "ADBC": 70.2,
    "ADBC_Scaled": 0.341,
    "Usurf": 0.0129,
    "Country_FR": "Cabo Verde",
    "name": "Praia",
    "Tpop": 527826,
    "X2": "Capital: Praia",
    "Surface": "Population: 525 000",
    "description": "Cabo Verde is the fifth smallest country in Africa in terms of surface area and the fourth smallest in terms of population. Its arid climate and steep relief make the country unfavorable to agriculture and have resulted in multiple famines over the course of its history. Since the 1950s, the population has steadily grown, going from 150 000 inhabitants in 1950 to 525 000 in 2015.\nCabo Verde is made up of hundreds of islands, but only nine are inhabited. The island of Santiago – where the capital Praia is located – accounts for 56% of the total population of the country. Historically, the capital Praia and the second city Mindelo have been of similar importance – the former due to its political status and the latter due to its location along the Atlantic trade routes. It is only after independence that Praia establishes itself as the more dominant city. By 2015, it was twice as large as Mindelo.\nIn 2015, Cabo Verde only counted four agglomerations with a population of more than 10 000 inhabitants. The Africapolis threshold of 10 000 inhabitants means that it is only since 2015 that Cabo Verde can be said to be mostly urban as the two smaller agglomerations Espargos and Assomada only counted 22 000 and 18 000 inhabitants respectively."
  },
  {
    "Country": "Djibouti",
    "ISO": "DJI",
    "ID": 11,
    "Upop": 688802,
    "Upop_Scaled": 0.173,
    "Ulvl_Scaled": 0.72,
    "NumAgglos": 7,
    "NumAgglos_Scaled": 0.006,
    "Mpop": 0.806,
    "ADBC": 30,
    "ADBC_Scaled": 0.146,
    "Usurf": 0.0033,
    "Country_FR": "Djibouti",
    "name": "Jibuti",
    "Tpop": 956669,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Algeria",
    "ISO": "DZA",
    "ID": 12,
    "Upop": 26630732,
    "Upop_Scaled": 0.394,
    "Ulvl_Scaled": 0.67,
    "NumAgglos": 488,
    "NumAgglos_Scaled": 0.421,
    "Mpop": 0.315,
    "ADBC": 97.9,
    "ADBC_Scaled": 0.476,
    "Usurf": 0.0031,
    "Country_FR": "Algérie",
    "name": "Algiers",
    "Tpop": 39747361,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Egypt",
    "ISO": "EGY",
    "ID": 13,
    "Upop": 84375765,
    "Upop_Scaled": 0.886,
    "Ulvl_Scaled": 0.93,
    "NumAgglos": 1061,
    "NumAgglos_Scaled": 0.916,
    "Mpop": 0.575,
    "ADBC": 19,
    "ADBC_Scaled": 0.092,
    "Usurf": 0.007,
    "Country_FR": "Égypte",
    "name": "Cairo",
    "Tpop": 90726629,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Eritrea",
    "ISO": "ERI",
    "ID": 14,
    "Upop": 1170085,
    "Upop_Scaled": 0.177,
    "Ulvl_Scaled": 0.24,
    "NumAgglos": 25,
    "NumAgglos_Scaled": 0.022,
    "Mpop": 0.398,
    "ADBC": 45.5,
    "ADBC_Scaled": 0.221,
    "Usurf": 0.0011,
    "Country_FR": "Érythrée",
    "name": "Asmara",
    "Tpop": 4875354,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Ethiopia",
    "ISO": "ETH",
    "ID": 15,
    "Upop": 24282232,
    "Upop_Scaled": 0.374,
    "Ulvl_Scaled": 0.27,
    "NumAgglos": 509,
    "NumAgglos_Scaled": 0.44,
    "Mpop": 0.419,
    "ADBC": 25.3,
    "ADBC_Scaled": 0.123,
    "Usurf": 0.0066,
    "Country_FR": "Éthiopie",
    "name": "Addis Abeba",
    "Tpop": 89934193,
    "X2": "Capital: Addis Ababa",
    "Surface": "Population: 90 078 000",
    "description": "In 2015, Ethiopia was the third most populous country in Africa behind Nigeria and Egypt. Most of the population lives in the mountainous area surrounding the Great Rift Valley but the population density declines in lower altitudes and towards the arid East and South-East which are less habitable. With an official urbanization level of just 27%, Ethiopia has the fifth lowest urbanization score in Africa.\nEthiopia’s urban population has increased rapidly since 2000, going from 6.5 million to 24.3 million in 2015. Over the same period, the number of agglomerations jumped from 147 to 509, a rise that is fueled by small and medium-sized agglomerations. The capital Addis Ababa is of modest size compared to other African countries and the primacy index has dropped quite sharply since 2010 as a result of the emergence of newer agglomerations.\nLike Nigeria and Rwanda, Ethiopia’s urbanization is driven by the continued densification of the rural areas. The second and third largest agglomerations, Sodo Town and Hawassa City – both located in foothills, do not have an urban center but are examples of in-situ urbanization that has resulted from the fusion of smaller but densely populated towns and villages. These two agglomerations alone account for a sixth of the total urban population.\nA third of the agglomerations in Ethiopia have emerged through in-situ urbanization. They challenge the very notion of urban agglomeration as in many cases, they retain a largely rural and agricultural character. If the current demographic trends persist - especially with regards to a fertility rate of more than 5 in rural areas - it is expected that Ethiopia will see the emergence of many more agglomerations of the same type."
  },
  {
    "Country": "Gabon",
    "ISO": "GAB",
    "ID": 16,
    "Upop": 1506156,
    "Upop_Scaled": 0.18,
    "Ulvl_Scaled": 0.81,
    "NumAgglos": 14,
    "NumAgglos_Scaled": 0.012,
    "Mpop": 0.588,
    "ADBC": 18.7,
    "ADBC_Scaled": 0.091,
    "Usurf": 0.0014,
    "Country_FR": "Gabon",
    "name": "Libreville",
    "Tpop": 1859452,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Equatorial Guinea",
    "ISO": "GNQ",
    "ID": 17,
    "Upop": 762000,
    "Upop_Scaled": 0.173,
    "Ulvl_Scaled": 0.62,
    "NumAgglos": 13,
    "NumAgglos_Scaled": 0.011,
    "Mpop": 0.746,
    "ADBC": 23.5,
    "ADBC_Scaled": 0.114,
    "Usurf": 0.0087,
    "Country_FR": "Guinée équatoriale",
    "name": "Malabo",
    "Tpop": 1229032,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Ghana",
    "ISO": "GHA",
    "ID": 18,
    "Upop": 14236199,
    "Upop_Scaled": 0.288,
    "Ulvl_Scaled": 0.52,
    "NumAgglos": 209,
    "NumAgglos_Scaled": 0.18,
    "Mpop": 0.579,
    "ADBC": 23.2,
    "ADBC_Scaled": 0.113,
    "Usurf": 0.0157,
    "Country_FR": "Ghana",
    "name": "Accra",
    "Tpop": 27377306,
    "X2": "Capital: Accra",
    "Surface": "Population: 27 403 000",
    "description": "In 2015, 52% of Ghana’s population lived in urban agglomerations of more than 10 000 inhabitants. The largest two cities, the capital Accra and Kumasi, account for half of the total urban population. The primacy index of Ghana is the second lowest in West Africa (after Nigeria), as Kumasi offers a counterweight to the dominance of the capital. Nonetheless, the urban hierarchy declines significantly after Kumasi: the third largest agglomeration (Takoradi) counts less than one-sixth of the capital’s population. The urban population density averages at 3 900 inhabitants per km2 – the third lowest in West Africa.\nUrbanization has progressed steadily since 1990. The total number of urban agglomerations has more than doubled from 87 in 1990 to 209 in 2015, with much of this growth stemming from the emergence of smaller agglomerations with populations between 10 000 and 50 000 inhabitants.\nHowever, the urban agglomerations are not spread out evenly across the territory. The southern part of the country, representing the former British Colony, accounts for half of all agglomerations and almost a third of the total population of the country in 2015. By contrast, the north is relatively under-urbanized and only counts 29 agglomerations. The agglomeration of Tamale dominates the north and holds a third of the urban population of the region. Similarly, the region to the east of the Volta basin (corresponding to the former Togoland), is dotted with many smaller agglomerations but together they account for just 1.5 million people, i.e. about 10% of the total urban population of the country."
  },
  {
    "Country": "Guinea",
    "ISO": "GIN",
    "ID": 19,
    "Upop": 4044553,
    "Upop_Scaled": 0.201,
    "Ulvl_Scaled": 0.37,
    "NumAgglos": 42,
    "NumAgglos_Scaled": 0.036,
    "Mpop": 0.541,
    "ADBC": 34.1,
    "ADBC_Scaled": 0.166,
    "Usurf": 0.0033,
    "Country_FR": "Guinée",
    "name": "Conakry",
    "Tpop": 10931224,
    "X2": "Capital: Conakry",
    "Surface": "Population: 10 924 000",
    "description": "In 2015, Guinea had a level of urbanization of 37% and counted a total of 42 urban agglomerations with more than 10 000 inhabitants – a relatively small number in view of the country’s size. Although urbanization has not progressed as rapidly as in other West African nations, Guinea has nonetheless registered an important increase in the total urban population, which jumped from 2.5 million in 2000 to just over 4 million in 2015.\nGuinea registers the fourth highest primacy index in Africa. The urban agglomeration of Conakry counts more than 2 million inhabitants and is more than 10 times larger than the second and third biggest cities Kankan and Nzérékoré. Similar to other West African capitals like Freetown and Dakar, Conakry is located on a peninsula with limited physical space to grow. The population density reaches more than 7 400 inhabitants per km2 compared to a country average of 5 020.\nWhereas the capital is home to more than half of all urban dwellers, smaller agglomerations make up only a fraction of the urban population. Instead, Guinea counts 2 urban agglomeration with more than 200 000 inhabitants (Kankan and Nzérékoré) and a further 4 that have between 100 000 and 200 000 inhabitants (Kindia, Kissigougou, Siguiri and Labé). Several of these are also regional capitals.\nIt is interesting to note that officially only Conakry and the regional capitals are labelled as “urban”. However, recently two urban agglomerations (Kamsar and Sangarédi), which have sprung up around mining sites, have been officially recognized as urban areas. In fact, several more urban agglomerations have emerged around mining sites since 2000 and it is expected that this trend will continue in the coming years and decades."
  },
  {
    "Country": "The Gambia",
    "ISO": "GMB",
    "ID": 20,
    "Upop": 1125753,
    "Upop_Scaled": 0.176,
    "Ulvl_Scaled": 0.56,
    "NumAgglos": 11,
    "NumAgglos_Scaled": 0.009,
    "Mpop": 0.701,
    "ADBC": 55.9,
    "ADBC_Scaled": 0.272,
    "Usurf": 0.0278,
    "Country_FR": "Gambie",
    "name": "Banjul",
    "Tpop": 2010273,
    "X2": "Capital: Banjul",
    "Surface": "Population: 2 024 000",
    "description": "The Gambia is the second smallest country in West Africa and surrounded on all three sides by Senegal. The Gambia river forms the core of the country which is no wider than 32km north to south. With a population of just over 2 million in 2015, the Gambia has the third highest population density in Africa at 235 inhabitants per km2.\nAt 56%, the Gambia’s level of urbanization is the highest in West Africa. Although the country counts 11 urban agglomerations in total, 4 of the largest (Serrakunda, Brikama, Tanjeh and Banjul) are located on the country’s coastline and are separated only by a few hundred meters of unconstructed land. These agglomerations are expected to form one big conurbation as their density increases, most likely reducing the total number of urban agglomerations in the country. Only 3 urban agglomerations of more than 10 000 inhabitants are located in the country’s interior where the level of urbanization barely exceeds 10%.\nThe Gambia’s biggest urban agglomeration is Serrekunda to the south of the capital Banjul. It counts 789 000 inhabitants and is 7 time larger than the second biggest agglomeration Brikama. Serrekunda alone accounts for 70% of the country’s urban population. By contrast, Banjul’s population has been in decline since the 1980s due to the limited size of the territory on which Banjul is built but also due to the emergence of newer urban agglomerations along the stretch of land that connects Banjul to the rest of the country."
  },
  {
    "Country": "Guinea-Bissau",
    "ISO": "GNB",
    "ID": 21,
    "Upop": 525458,
    "Upop_Scaled": 0.171,
    "Ulvl_Scaled": 0.34,
    "NumAgglos": 6,
    "NumAgglos_Scaled": 0.005,
    "Mpop": 0.781,
    "ADBC": 25.5,
    "ADBC_Scaled": 0.124,
    "Usurf": 0.0034,
    "Country_FR": "Guinée-Bissau",
    "name": "Bissau",
    "Tpop": 1545465,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Kenya",
    "ISO": "KEN",
    "ID": 22,
    "Upop": 28559230,
    "Upop_Scaled": 0.41,
    "Ulvl_Scaled": 0.65,
    "NumAgglos": 126,
    "NumAgglos_Scaled": 0.109,
    "Mpop": 0.793,
    "ADBC": 65.1,
    "ADBC_Scaled": 0.316,
    "Usurf": 0.0403,
    "Country_FR": "Kenya",
    "name": "Nairobi",
    "Tpop": 43937277,
    "X2": "Capital: Nairobi",
    "Surface": "Population: 44 157 000",
    "description": "Kenya has the third highest levels of urbanisation in Africa at 65%. The definition of what counts as a city is largely political and recognizes only the core of the cities. However, in reality urban agglomerations not recognized as forming part of cities are integral to Kenya’s urban landscape. Five of these agglomerations (Nairobi, Kisumu, Kisii, Embu and Mombasa) have more than 1 million inhabitants and six have more than 400 000.\nThese urban agglomerations often expand over a large territory and have relatively low population densities compared to agglomerations in other African countries (on average 1235 inhabitants/km2 which gives Kenya the second lowest urban population density in Africa behind Swaziland). Most of the urban agglomerations can be found in Kenya’s highlands whereas littoral areas are more sparsely populated. Outside of Mombasa, there are very few if any urban agglomerations along the coastline.\nMost of the urban population growth is happening in larger agglomerations above 200 000 inhabitants. Smaller cities and urban agglomerations are growing much slower. The largest agglomerations can be found in the Western highlands and north of Nairobi in the central part of the country. These two hold a combined population of more than 26 million and are likely to become two of the largest urban agglomerations in Africa in the years to come, extending over several hundreds of kilometers."
  },
  {
    "Country": "Liberia",
    "ISO": "LBR",
    "ID": 23,
    "Upop": 1715625,
    "Upop_Scaled": 0.181,
    "Ulvl_Scaled": 0.42,
    "NumAgglos": 21,
    "NumAgglos_Scaled": 0.018,
    "Mpop": 0.694,
    "ADBC": 36.9,
    "ADBC_Scaled": 0.179,
    "Usurf": 0.0044,
    "Country_FR": "Libéria",
    "name": "Monrovia",
    "Tpop": 4084821,
    "X2": "Capital: Monrovia",
    "Surface": "Population: 4 045 000",
    "description": "In 2015, Liberia had a total population of around 4 million. Whilst 42% of this population lives in urban agglomerations, in reality the majority is concentrated in the capital Monrovia, which alone accounts for two-thirds of the total urban population of the country. Outside of Monrovia, the country only counts 20 other urban agglomerations, none of which have more than 60 000 inhabitants (compared to 1 191 000 inhabitants in Monrovia). This gives Liberia the highest primacy index of any country in the world. The dominance of Monrovia is so pronounced that the level of urbanization in the country would only reach 18.4% if Monrovia were discounted.\nThe population of Liberia is very unevenly distributed. Of the six largest agglomerations, five (Monrovia, Ganta, Kakata, Gbarnga and Harbel) are located along the crest between the rivers Saint Paul and Saint John that connects Monrovia to Ganta at the Guinean border. The Southern part of the country is very sparsely populated and the road infrastructure connecting various localities is very poorly developed.\nUnlike many other African countries, Liberia has experienced very little growth in the number of urban agglomerations. Between 1980 and 2000, the number of urban agglomerations remained stable at 14 but increased to 24 by 2010. In 2015, the number stood at 21 urban agglomerations. This decline is due to the disappearance in 2012 of three refugee camps that counted more than 10 000 inhabitants. The appearance and disappearance of urban agglomerations is also linked to mining activities that have given rise to new settlements but also triggered their dissipation once mining operations closed."
  },
  {
    "Country": "Libya",
    "ISO": "LBY",
    "ID": 24,
    "Upop": 4410899,
    "Upop_Scaled": 0.204,
    "Ulvl_Scaled": 0.81,
    "NumAgglos": 46,
    "NumAgglos_Scaled": 0.04,
    "Mpop": 0.642,
    "ADBC": 50.2,
    "ADBC_Scaled": 0.244,
    "Usurf": 0.0019,
    "Country_FR": "Libye",
    "name": "Tripoli",
    "Tpop": 5445554,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Lesotho",
    "ISO": "LSO",
    "ID": 25,
    "Upop": 525088,
    "Upop_Scaled": 0.171,
    "Ulvl_Scaled": 0.26,
    "NumAgglos": 10,
    "NumAgglos_Scaled": 0.009,
    "Mpop": 0.584,
    "ADBC": 21.3,
    "ADBC_Scaled": 0.103,
    "Usurf": 0.0104,
    "Country_FR": "Lesotho",
    "name": "Maseru",
    "Tpop": 2019569,
    "X2": "Capital: Maseru",
    "Surface": "Population: 1 999 000",
    "description": "Lesotho is one of Africa’s smallest countries and has the lowest level of urbanization in Southern Africa at 26.3%. Compared to other African countries, the level of urbanization has only progressed slowly in Lesotho.\nThe capital Maseru stands out amongst Lesotho’s urban agglomerations. It is almost 9 times larger than the second largest city Maputsoe and counts a total of 307 000 inhabitants in the wider agglomeration. Nonetheless, it remains of modest size and – unlike most African capitals – it only counts as a medium-sized agglomeration.\nSince 1990, Maseru has started to spread out to the North, and later to the South. In 2015, 124 000 of Maseru’s inhabitants were living in the periphery of the city. Overall, the city accounts for more than half of all urban dwellers in Lesotho.\nThe country retains a predominantly rural character. Most of the larger urban agglomerations are situated along the north-western border with South Africa whereas the interior is largely rural. The population densities in the urban agglomerations is one of the lowest in Africa at just 1 644 inhabitants per km2."
  },
  {
    "Country": "Morocco",
    "ISO": "MAR",
    "ID": 26,
    "Upop": 17287822,
    "Upop_Scaled": 0.314,
    "Ulvl_Scaled": 0.51,
    "NumAgglos": 170,
    "NumAgglos_Scaled": 0.147,
    "Mpop": 0.579,
    "ADBC": 81,
    "ADBC_Scaled": 0.394,
    "Usurf": 0.0043,
    "Country_FR": "Maroc",
    "name": "Rabat",
    "Tpop": 33897690,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Mali",
    "ISO": "MLI",
    "ID": 27,
    "Upop": 5697331,
    "Upop_Scaled": 0.215,
    "Ulvl_Scaled": 0.32,
    "NumAgglos": 94,
    "NumAgglos_Scaled": 0.081,
    "Mpop": 0.537,
    "ADBC": 65.2,
    "ADBC_Scaled": 0.317,
    "Usurf": 0.0009,
    "Country_FR": "Mali",
    "name": "Bamako",
    "Tpop": 17804159,
    "X2": "Capital: Bamako",
    "Surface": "Population: 17 819 000",
    "description": "Mali has the second lowest population density in West Africa (behind Mauritania) at 14 inhabitants per square km. The population is very unevenly distributed across the territory: two-thirds of the territory - comprising mainly the regions of Timbuktu, Gao and Kidal - account for only 778 000 inhabitants in 2015 (i.e. less than 1 inhabitant/km2), of which a large majority is concentrated in the regional capitals. 96% of the Malian population lives in the other third of the territory, corresponding to a population density of 47 inhabitants/km2.\nThe capital Bamako dominates the urban population distribution by accounting for almost half of all urban dwellers. It is 10 times as large as the second biggest city Sikasso, both in terms of inhabitants and surface area. Mali’s primacy index is the sixth largest in Africa. However, the number of smaller urban agglomerations between 10,000 and 49,999 inhabitants has seen large growth in the past few decades. In 1990, there were only 18 urban agglomerations in this category, but the number grew to XX in 2015.\nMali has one of the highest urban growth rates on the African continent. Only 18% of the total population were living in urban agglomerations in 1990. In 2015, the level of urbanisation stood at 32%. At the same time, the country has seen significant population growth (from 8.2 to 15.2 million) which has also translated into a larger urban population (from 1.5 to 5.7 million)."
  },
  {
    "Country": "Mozambique",
    "ISO": "MOZ",
    "ID": 28,
    "Upop": 8772349,
    "Upop_Scaled": 0.241,
    "Ulvl_Scaled": 0.33,
    "NumAgglos": 157,
    "NumAgglos_Scaled": 0.136,
    "Mpop": 0.476,
    "ADBC": 129.5,
    "ADBC_Scaled": 0.629,
    "Usurf": 0.0036,
    "Country_FR": "Mozambique",
    "name": "Maputo",
    "Tpop": 26582876,
    "X2": "Capital: Maputo",
    "Surface": "Population: 26 961 000",
    "description": "Mozambique officially counts 88 cities of which 77 have a population of more than 10 000 inhabitants. However, Geopolis data shows that there are as many as 157 separate urban agglomerations. The biggest agglomeration is the capital Maputo which counts 2.6 million inhabitants. In addition to Maputo, there are four more agglomerations that count more than 300 000 inhabitants (Beira, Nampula, Chimoio and Quelimane). Many of the smaller agglomerations that have emerged recently are located further inland.\nUntil the 1970s, Mozambique remains largely rural with a level of urbanization below 10% and a total of just 6 urban agglomerations within its territory. By 1990, that figure had increased to 17.6% and 15 urban agglomerations in total. Urbanization however takes off after 1990 when the country experiences a tripling of the number of urban agglomerations within just 10 years to 65 in 2000 and then another increase in recent years to bring the number to 157. This growth is largely driven by the rapid increase in smaller agglomerations between 10 000 and 50 000 inhabitants.\nMozambique’s urban agglomerations are relatively evenly distributed across the territory. Despite the relatively small number of agglomerations for a country of Mozambique’s size, the average distance between agglomerations is quite low (38km in 2010). Amongst the newer agglomerations, two different kinds can be distinguished: large circular towns with low densities and hyper-linear towns that emerge around the road networks. These agglomerations are often characterized by a lack of infrastructure and the predominance of agricultural activities and roadside businesses. Many of these agglomerations also display low levels of density (3 138 inhabitants per km2 on average in 2015)."
  },
  {
    "Country": "Mauritania",
    "ISO": "MRT",
    "ID": 29,
    "Upop": 1713049,
    "Upop_Scaled": 0.181,
    "Ulvl_Scaled": 0.42,
    "NumAgglos": 23,
    "NumAgglos_Scaled": 0.02,
    "Mpop": 0.619,
    "ADBC": 73.7,
    "ADBC_Scaled": 0.358,
    "Usurf": 0.0004,
    "Country_FR": "Mauritanie",
    "name": "Nouakchott",
    "Tpop": 4078688,
    "X2": "Capital: Nouakchott",
    "Surface": "Population: 3 773 000",
    "description": "Mauritania is the third largest West African country by surface area (behind Mali and Niger) and has the second lowest population density in Africa behind Namibia at just 4 inhabitants per km2 (on par with Botswana). Three quarters of the country are dominated by desert or semi-desert. Most of the population lives along the coast and along the border with Senegal and Mali to the South (valley of the Senegal river).\nUrbanization has increased rapidly since 2000. The urban population has more than doubled from 836 000 to 1 713 000 in 2015. Over the same period, the number of urban agglomerations has jumped from 12 to 23, an increase that is mainly due to the emergence of smaller agglomerations between 10 000 and 50 000 inhabitants.\nThe capital Nouakchott dominates the country’s urban profile. It is home to 28% of the total population, 62% of all urban dwellers and is 8 times as large as the second biggest city Nouadhibou. The emergence of Nouakchott is a relatively recent phenomenon: in 1960, it only counted 416 inhabitants compared to 1 million in 2015. Aside from the capital, the other main settlement areas have emerged around sites of economic activity: the iron mining town of Zoueiratt, which links to the main port of Nouadhibou, and the Senegal valley where the urban agglomerations of Kaedi, Kiffa and Mbera are located. The latter is the fourth largest urban agglomeration in Mauritania but is in fact a refugee camp with an extraordinary urban population density of more than 15 000 inhabitants per km2."
  },
  {
    "Country": "Malawi",
    "ISO": "MWI",
    "ID": 30,
    "Upop": 4835999,
    "Upop_Scaled": 0.208,
    "Ulvl_Scaled": 0.3,
    "NumAgglos": 77,
    "NumAgglos_Scaled": 0.066,
    "Mpop": 0.51,
    "ADBC": 72.5,
    "ADBC_Scaled": 0.352,
    "Usurf": 0.0129,
    "Country_FR": "Malawi",
    "name": "Lilongwe",
    "Tpop": 16119997,
    "X2": "Capital: Lilongwe",
    "Surface": "Population: 16 310 000",
    "description": "Malawi has four official cities and 28 rural market towns. The country’s urbanisation profile is unique in Africa as the country does not count one but two dominant cities, Lilongwe and Blantyre, which are of similar size. Indeed, Malawi has the lowest primacy index of any country in the world. At the same time, it has one of the highest population densities in Africa at 173 inhabitants/km2.\nBesides Lilongwe and Blantyre, Malawi only counts two further cities with more than 200 000 inhabitants (Zomba and Mzuzu) and one urban agglomeration of more than 100 000 inhabitants (Mpama/Likoswe UA). Until 25 years ago, Malawi was largely rural with a level of urbanisation of just 10% in 1990. Since then, urbanisation has largely been driven by people setting up informal settlements, thereby driving urbanisation outside of an official planning framework. Today, there are 73 urban agglomerations in the country (up from 13 in 1990), but more than half of these agglomerations are not officially recognized as urban areas. Nonetheless, Malawi remains the second least urbanized country in Central Africa at a level of 29.6%.\nMalawi’s “improvised” agglomerations present a significant challenge for managed urbanisation. Unlike many other African nations, there is no real rural exodus. Instead urban agglomerations are built by the people themselves without the need to migrate towards cities per se. Policy-makers remain reluctant to provide more powers to the lowest administrative level, the Traditional Authorities, which often cover very large areas (on average 450 km2 with 67,000 inhabitants) without having the resources to provide adequate planning and development support."
  },
  {
    "Country": "Namibia",
    "ISO": "NAM",
    "ID": 31,
    "Upop": 891180,
    "Upop_Scaled": 0.174,
    "Ulvl_Scaled": 0.4,
    "NumAgglos": 17,
    "NumAgglos_Scaled": 0.015,
    "Mpop": 0.401,
    "ADBC": 22.9,
    "ADBC_Scaled": 0.111,
    "Usurf": 0.0004,
    "Country_FR": "Namibie",
    "name": "Windhoek",
    "Tpop": 2227950,
    "X2": "Capital: Windhoek",
    "Surface": "Population: 2 210 000",
    "description": "Namibia is Africa’s least densely populated country with an average of just 3 inhabitants per square km. The country consists mainly of high plateau which is flanked by the Namib desert along the Western coastline and the Kalahari Desert to the East, rendering large swaths of the country unfavorable to human occupation. Whilst the urban population has more than doubled since 1990, the pace of urbanisation has slowed down in the past decade compared to previous decades, mainly as a result of the limited demographic resources of Namibia’s sparsely populated hinterland.\nThe country is subdivided into 14 regions and 121 constituencies and counts 17 urban agglomerations with a population above 10 000 – the biggest being the capital Windhoek with just under 360 000 inhabitants. Most of the other larger urban agglomerations such as Rundu, Walvis Bay, Oshakati and Swakopmund are situated on the country’s borders which magnifies the relative “emptiness” of the interior parts of the country. The overall level of urbanisation stands at 40% but the population density in the urban agglomerations is the fifth lowest in Africa at 2 804 inhabitants/ km2.\nContrary to most African nations, there are few agglomerations below 20,000 inhabitants and 13 out of the 17 cities have populations between 20 000 and 40 000. Whilst the distance between urban agglomerations has gradually decreased as more cities emerge and existing cities grow, the average distance between cities remains high by African standards at 107 km."
  },
  {
    "Country": "Niger",
    "ISO": "NER",
    "ID": 32,
    "Upop": 3270216,
    "Upop_Scaled": 0.195,
    "Ulvl_Scaled": 0.17,
    "NumAgglos": 68,
    "NumAgglos_Scaled": 0.059,
    "Mpop": 0.518,
    "ADBC": 50.8,
    "ADBC_Scaled": 0.247,
    "Usurf": 0.0005,
    "Country_FR": "Niger",
    "name": "Niamey",
    "Tpop": 19236565,
    "X2": "Capital: Niamey",
    "Surface": "Population: 18 851 000",
    "description": "Niger has the lowest level of urbanization in Africa at just 17.3%. Unlike many other African countries, its level of urbanization has not increased much since 1990 when it stood at 14%. However, the total number of agglomerations has increased sharply over that period, jumping from 24 to 68 in 2015. This growth has been largely driven by an increase in the number of smaller agglomerations with fewer than 50 000 inhabitants, which accounted for a third of the urban population in 2015.\nWith a population of 18.9 million spread out over a relatively vast territory, Niger also has the third lowest population density in West Africa at 16 inhabitants per km2 against an average of 29 for the region. However, 96% of the population lives in the Southern half of the country which only represents a quarter of the surface. Here, densities approach an average of 60 inhabitants per km2. Within the urban agglomerations, this density is as high as 5 947 inhabitants per km2 in 2015. This high urban density is the result of the relative absence of sprawl which characterizes most of the country’s cities.\nIn addition to the capital Niamey, there are four more urban agglomerations counting more than 100 000 inhabitants: Maradi, Zinder, Tahoua and Agadez. Despite Niamey’s extraordinary growth (going from 8 300 inhabitants in 1950 to over a million in 2015), Maradi and Zinder are gradually transforming into strategically important cities rivaling the capital due to their location at the Nigerian border."
  },
  {
    "Country": "Nigeria",
    "ISO": "NGA",
    "ID": 33,
    "Upop": 97780052,
    "Upop_Scaled": 1,
    "Ulvl_Scaled": 0.52,
    "NumAgglos": 1158,
    "NumAgglos_Scaled": 1,
    "Mpop": 0.609,
    "ADBC": 66.5,
    "ADBC_Scaled": 0.323,
    "Usurf": 0.0218,
    "Country_FR": "Nigéria",
    "name": "Abuja",
    "Tpop": 188038562,
    "X2": "Capital: Abuja",
    "Surface": "Population: 186 940 000",
    "description": "The territory of modern-day Nigeria has given rise to some of Africa’s most important pre-colonial cities. By 1890, Nigeria was already home to more than twenty cities with a population of more than 20 000 inhabitants and by 1911 the country counted more cities with populations above 10 000 than the rest of Sub-Saharan Africa combined.\nToday, Nigeria is the most populous country in Africa and has the second highest level of urbanization (52%) in West Africa after the Gambia. Its population density is the fourth highest in Africa at 205 inhabitants per km2. The demographic weight of Nigeria is a key factor in explaining not just the high number of urban agglomerations but also their relatively large size.\nAccording to Africapolis, Nigeria accommodates 1 158 urban agglomerations, making it the country with the largest number of urban agglomerations in Africa. Unlike the rest of the region, Nigeria is characterized by the large number of medium-sized cities with populations between 50 000 and 500 000. Many of these are located in the Southern part of the country but the sheer number of urban agglomerations overall means that the whole territory represents one extensive urban network.\nIn 2015, just over half of all urban dwellers lived in agglomerations of more than 500 000 inhabitants. The most populous city (Lagos) accounts for about 12% of the country’s urban population. Lagos and Kano (the third largest agglomeration) both score urban density levels above 12 500 inhabitants per km2 compared to a national average of just 4 959. In fact, some of Nigeria’s largest urban agglomerations such as Onitsha, Aba and Uyo, are spread out over vast territories. Onitsha is the second largest urban agglomeration in Nigeria but covers an area ten times as large as that of Kano."
  },
  {
    "Country": "Rwanda",
    "ISO": "RWA",
    "ID": 34,
    "Upop": 6335276,
    "Upop_Scaled": 0.221,
    "Ulvl_Scaled": 0.56,
    "NumAgglos": 41,
    "NumAgglos_Scaled": 0.035,
    "Mpop": 0.611,
    "ADBC": 33.3,
    "ADBC_Scaled": 0.162,
    "Usurf": 0.0877,
    "Country_FR": "Rwanda",
    "name": "Kigali",
    "Tpop": 11312993,
    "X2": "Capital: Kigali",
    "Surface": "Population: 11 346 000",
    "description": "Rwanda’s official level of urbanization stands at 17% against a level of 56% estimated by Africapolis based on its morphological approach. In fact, Rwanda has one of the highest levels of urbanization in Africa, largely as a result of the phenomenal densification of rural areas. At 446 inhabitants per km2 nationally, Rwanda has the highest average population density in Africa and almost double the density of the second ranking country (the Gambia).\nUrbanization has grown spectacularly over the past 3 decades. The total urban population grew 6-fold between 1990 and 2000 to reach 2 million, before tripling again to attain 6.3 million in 2015. Similarly, the level of urbanization has increased from 5% in 1990, to 26% in 2000 before reaching 56% in 2015. Over the same period, the country has seen a rapid increase in the number of agglomerations which went from just 7 in 1990 to 53 in 2000. In 2015, the number reduced to 41 agglomerations as a result of the fusion of several agglomerations into greater conurbations. This is reflected in the quasi absence of very small agglomerations between 10 000 and 20 000 inhabitants in 2015.\nThe capital Kigali holds slightly more than one third of the urban population. It is twice as large as the second biggest agglomeration Gisenyi but its dominance has reduced massively since 2000 when Kigali was almost 15 times larger than the second biggest agglomeration. Medium-sized agglomerations account for another third whereas smaller agglomerations account for only 8% of the total urban population.\nThe urban network itself is strongly interconnected. From the capital Kigali, located at the centre of the country, a web of agglomerations extends practically all the way to Uganda and Congo in the North and towards Burundi in the South."
  },
  {
    "Country": "South Sudan",
    "ISO": "SSD",
    "ID": 35,
    "Upop": 3361900,
    "Upop_Scaled": 0.195,
    "Ulvl_Scaled": 0.27,
    "NumAgglos": 90,
    "NumAgglos_Scaled": 0.078,
    "Mpop": 0.114,
    "ADBC": 196.6,
    "ADBC_Scaled": 0.955,
    "Usurf": 0.0018,
    "Country_FR": "Soudan du Sud",
    "name": "NA",
    "Tpop": 12451481,
    "X2": "Capital: Juba",
    "Surface": "Population: 12 408 000",
    "description": "South Sudan is the newest nation in Africa, formed in 2011 after an independence referendum. It is completely landlocked and borders on several states that themselves are landlocked (Chad, Uganda, Ethiopia). The population density is relatively low at 19 inhabitants per km2 and the urban population density is the sixth lowest in Africa at just 2 893 inhabitants per km2.\nThe population is unevenly distributed, and some parts of South Sudan are largely uninhabited. Most of the urban agglomerations are located along the Southern border with Uganda and in the marshlands between the Western plateau and the White Nile. In 2015, slightly more than a quarter of the population lived in urban agglomerations. It has the fourth lowest level of urbanization in Africa despite a strong increase in the past two decades which has seen the level of urbanization grow from 12% in 2000 to the current level of 27%.\nOfficial urbanization and population data for South Sudan is however not very reliable. Civil unrest has caused significant population movements in recent years. Between 2012 and 2015, ten urban agglomerations of more than 10 000 inhabitants were either totally or partially destructed. Several urban agglomerations that were refugee camps have either moved or disappeared.\nAfricapolis has counted 66 more urban agglomerations than are officially captured. Several of these are composed of dwellings and buildings made of organic materials with very little infrastructure constructed from hard materials and a quasi-absence of roads. These non-permanent structures are not officially recognized and therefore national statistics underestimate the true extent of urbanization in South Sudan."
  },
  {
    "Country": "Senegal",
    "ISO": "SEN",
    "ID": 36,
    "Upop": 7156859,
    "Upop_Scaled": 0.228,
    "Ulvl_Scaled": 0.51,
    "NumAgglos": 74,
    "NumAgglos_Scaled": 0.064,
    "Mpop": 0.681,
    "ADBC": 38.6,
    "ADBC_Scaled": 0.188,
    "Usurf": 0.0049,
    "Country_FR": "Sénégal",
    "name": "Dakar",
    "Tpop": 14033057,
    "X2": "Capital: Dakar",
    "Surface": "Population: 14 143 000",
    "description": "In 2015, around half of the population of Senegal lived in urban agglomerations. The capital Dakar outweighs all other agglomerations in the country: it is three-and-a-half times larger than the second agglomeration (Touba), and almost 9 times larger than the third biggest (Thiès). Dakar alone reaches one of the highest population densities of any African capital at 15 052 inhabitants per km2. The average urban population density is the third highest in Africa at 7 459 inhabitants per km2.\nSenegal counts a total of 74 urban agglomerations and a large part of these is located in one of the 9 departments surrounding Dakar (Bambey, Diourbel, M’Backé, M’bour, Thiès, Fatick, Tivaouane, Guinguinéo et Kaolack), including the 5 most populous agglomerations of the country. In fact, Dakar and the surrounding 9 departments hold more than half of the country’s total population but only represent 8.7% of the territory. The level of urbanization in this zone is as high as 73% against 23% in the rest of the country. It is expected that in a few years, the wider area will become one large metropolitan area.\nBesides Dakar, there are only a few agglomerations dotted along the coastline. If one excludes Saint Louis, M’bour and Dakar, the country only counts two more agglomerations along the coast. Instead, many of the agglomerations are located along the old railway line connecting Dakar to Niger and along the Senegal River which marks the border with Mauritania. It is here that many smaller agglomerations with more than 2 000 inhabitants (but fewer than 10 000) are starting to appear."
  },
  {
    "Country": "Sierra Leone",
    "ISO": "SLE",
    "ID": 37,
    "Upop": 2592400,
    "Upop_Scaled": 0.189,
    "Ulvl_Scaled": 0.37,
    "NumAgglos": 25,
    "NumAgglos_Scaled": 0.022,
    "Mpop": 0.562,
    "ADBC": 15.5,
    "ADBC_Scaled": 0.075,
    "Usurf": 0.0062,
    "Country_FR": "Sierra Leone",
    "name": "Freetown",
    "Tpop": 7006486,
    "X2": "Capital: Freetown",
    "Surface": "Population: 7 092 000",
    "description": "Sierra Leone’s urbanization profile is marked by the predominance of its capital Freetown, which is 7 times larger than the second biggest city Kenema and assembles more than half of the total urban population in the country. The overall level of urbanization stands at 36.6% in 2015 but outside of the capital the level is just 18.8%. The average urban population density is 5 780 inhabitants per km2, the sixth highest in Africa.\nThe dominance of Freetown is related to the establishment of the capital at the extreme Western end of the country, on the peninsula that formed the former British Crown Colony of Sierra Leone in 1808 and today corresponds to the Western Area. The interior of the country was only demarcated at the end of the 19th century and remains poorly connected to the capital. Much of the interior’s infrastructure was also destroyed during the civil war that lasted from 1991 to 2002 and which further catalyzed the concentration of the urban population. Outside of Freetown, the main urban centers are the provincial capitals of Kenema, Bo and Makeni and the diamond-mining town of Koidu, which all have populations between 100 000 and 200 000. By contrast, the smaller agglomerations between 10 000 and 50 000 people only represent 15% of the urban population but the number of smaller agglomerations is rising rapidly."
  },
  {
    "Country": "Somalia",
    "ISO": "SOM",
    "ID": 38,
    "Upop": 4554400,
    "Upop_Scaled": 0.205,
    "Ulvl_Scaled": 0.36,
    "NumAgglos": 49,
    "NumAgglos_Scaled": 0.042,
    "Mpop": 0.531,
    "ADBC": 37,
    "ADBC_Scaled": 0.18,
    "Usurf": 0.0008,
    "Country_FR": "Somalie",
    "name": "Mogadishu",
    "Tpop": 12651111,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Sao Tome and Principe",
    "ISO": "STP",
    "ID": 39,
    "Upop": 160051,
    "Upop_Scaled": 0.168,
    "Ulvl_Scaled": 0.8,
    "NumAgglos": 3,
    "NumAgglos_Scaled": 0.003,
    "Mpop": 0,
    "ADBC": 53.9,
    "ADBC_Scaled": 0.262,
    "Usurf": 0.0438,
    "Country_FR": "Sao Tomé-et-Principe",
    "name": "Sao Tome",
    "Tpop": 200064,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Sudan",
    "ISO": "SDN",
    "ID": 40,
    "Upop": 16028255,
    "Upop_Scaled": 0.303,
    "Ulvl_Scaled": 0.42,
    "NumAgglos": 280,
    "NumAgglos_Scaled": 0.242,
    "Mpop": 0.512,
    "ADBC": 205.8,
    "ADBC_Scaled": 1,
    "Usurf": 0.0018,
    "Country_FR": "Soudan",
    "name": "Khartoum",
    "Tpop": 38162512,
    "X2": "Capital: Khartoum",
    "Surface": "Population: 38 435 000",
    "description": "Sudan is the third largest country in Africa after Algeria and DR Congo. The climate ranges from arid deserts in the northern two-thirds of the country to semi-arid in the south and some pockets of tropical savannah in the southern-most regions. The North-Western part of the country is largely uninhabited.\nIn 1950, Sudan was the most urbanized country of East Africa (8%). The level of urbanisation remains high and has gone up from 30% in 1990 to 42% in 2015. Over the same period, the number of urban agglomerations has multiplied from 78 to 280 agglomerations in 2015, giving it the fifth highest number of urban agglomerations in Africa. The largest growth can be seen in the number of small towns and cities with fewer than 100 000 inhabitants. Whilst there were only 69 such cities in 1990, there were 205 cities in this category in 2010. The politico-administrative framework has not kept pace with these changes: in 2008, only 96 agglomerations with more than 10 000 inhabitants were formally classified as cities whereas the country counted more than 200 agglomerations of similar size.\nUrbanisation in Sudan is also characterized by a relatively large urban primacy index, the largest in East Africa. The capital Khartoum is almost 10 times as large as the second city Nyala, both in terms of population and built area. The region of Jazira, within which the capital is located, is largely arid except for the delta between the two Nile rivers that have historically provided opportunities for the development of sophisticated irrigation techniques and have thereby contributed to high population growth in an otherwise barren region. This area of 20 000 square km, representing only 1.1% of Sudan’s overall surface area, accounts for 44% of the total urban population of the country."
  },
  {
    "Country": "Swaziland",
    "ISO": "SWZ",
    "ID": 41,
    "Upop": 300643,
    "Upop_Scaled": 0.169,
    "Ulvl_Scaled": 0.28,
    "NumAgglos": 5,
    "NumAgglos_Scaled": 0.004,
    "Mpop": 0,
    "ADBC": 36.6,
    "ADBC_Scaled": 0.178,
    "Usurf": 0.0219,
    "Country_FR": "Kingdom of Eswatini",
    "name": "Mbabane",
    "Tpop": 1073725,
    "X2": "Capital: Mbabane",
    "Surface": "Population: 1 079 000",
    "description": "Swaziland is the second smallest country on the African continent after the Gambia. Urbanization has progressed only slowly, and the country remains predominantly rural. The level of urbanization has barely increased since 2000 when it stood at 25.5% against 28% in 2015. Only about 50 000 more people were added to the total urban population during that time. This trend is likely to continue as population growth has practically stagnated at less than 1%.\nAfricapolis only identified five agglomerations with more than 10 000 inhabitants and the three smallest of these (Mafutseni, Nhlangano and Mahamba) are not officially recognized as cities. The total number of urban agglomerations has not changed since 2000.\nIn 2015, Swaziland was home to slightly more than a million people. The biggest agglomerations are Mbabane and Manzini which have populations of 136 000 and 110 000 respectively. However, the urban population is relatively spread out and even the two largest agglomerations exhibit vast plots of land without any constructions. The average urban population density is the lowest of any African country at just 797 inhabitants per km2."
  },
  {
    "Country": "Chad",
    "ISO": "TCD",
    "ID": 42,
    "Upop": 3899403,
    "Upop_Scaled": 0.2,
    "Ulvl_Scaled": 0.29,
    "NumAgglos": 93,
    "NumAgglos_Scaled": 0.08,
    "Mpop": 0.31,
    "ADBC": 143.4,
    "ADBC_Scaled": 0.697,
    "Usurf": 0.0006,
    "Country_FR": "Tchad",
    "name": "N'Djamena",
    "Tpop": 13446217,
    "X2": "Capital: N’Djamena",
    "Surface": "Population: 13 670 000",
    "description": "Chad is one of the largest African countries in terms of its surface area. It is of similar size than Niger and Mali but has fewer people and one of the lowest population densities in Africa at just 11 inhabitants per km2. Chad is surrounded by several countries in conflict, which explains the relatively large population of refugees (around 380’000). Despite the inclusion of 19 refugee camps with more than 10 000 inhabitants, Africapolis estimates the country’s level of urbanization at only 28.5%, the lowest in West Africa after Niger.\nChad’s urban population has grown steadily, jumping from 1.6 million in 2000 to 3.9 million in 2015. During this period, the total number of agglomerations with more than 10 000 inhabitants has increased from 37 to 93. 45% of the urban population lives in smaller agglomerations of fewer than 50 000 inhabitants.\nThe capital N’Djamena, which accounts for a third of the urban population, dominates the urban landscape. With a population of 1.2 million in 2015, it is almost 8 times larger than the second biggest agglomeration Moundou. Chad’s other major agglomerations have populations of less than 160 000. Their modest size is due in part to their relative distance from N’Djamena and other regional capitals. Most of Chad’s urban agglomerations are located along the East-West axis from Lake Chad to the Sudanese border and along the Chari river, flowing south-east from the Lake towards the Central-African border."
  },
  {
    "Country": "Togo",
    "ISO": "TGO",
    "ID": 43,
    "Upop": 3416245,
    "Upop_Scaled": 0.196,
    "Ulvl_Scaled": 0.5,
    "NumAgglos": 54,
    "NumAgglos_Scaled": 0.047,
    "Mpop": 0.507,
    "ADBC": 26.4,
    "ADBC_Scaled": 0.128,
    "Usurf": 0.0171,
    "Country_FR": "Togo",
    "name": "Lome",
    "Tpop": 6832490,
    "X2": "Capital: Lomé",
    "Surface": "Population: 6 835 000",
    "description": "Togo’s urban profile is characterized by the striking dominance of its capital Lomé whose size encompasses most of Togo’s coastal front. The country has the fifth highest primacy index in Africa. With a population of 1.7 million, the agglomeration of Lomé is ten times as large as the second biggest agglomeration Tsévié despite only covering an area three times as large. Slightly more than half of all urban dwellers in the country and a quarter of the total population reside in the Lomé agglomeration.\nDespite its relatively small surface area, the country counted 54 urban agglomerations in 2015. This represents a doubling of the number of urban agglomerations in just 15 years. Over the same period of time, the urban population has practically tripled from 1 264 000 in 2000 to 3 416 000 in 2015. Some of these newer agglomerations have emerged around secondary cities or through the fusion of multiple villages. This is for instance the case of Kana in the North of Togo, which over time is expected to merge with smaller agglomerations in its vicinity to create a larger conurbation.\nThe urbanization process in Togo can be described as somewhat anarchic. It is typified by the continuous encroachment of the urban agglomerations onto the rural areas through the expansion of the built environment. This sprawl derives from inadequate planning laws that encourage spontaneous construction by homebuilders. It poses a challenge not just for the surrounding rural areas but also in terms of the provision of basic social services such as drinking water, electricity or healthcare."
  },
  {
    "Country": "Tunisia",
    "ISO": "TUN",
    "ID": 44,
    "Upop": 7010411,
    "Upop_Scaled": 0.226,
    "Ulvl_Scaled": 0.63,
    "NumAgglos": 89,
    "NumAgglos_Scaled": 0.077,
    "Mpop": 0.504,
    "ADBC": 20.9,
    "ADBC_Scaled": 0.102,
    "Usurf": 0.0115,
    "Country_FR": "Tunisie",
    "name": "Tunis",
    "Tpop": 11127637,
    "X2": "NA",
    "Surface": "NA",
    "description": "NA"
  },
  {
    "Country": "Tanzania",
    "ISO": "TZA",
    "ID": 45,
    "Upop": 18567243,
    "Upop_Scaled": 0.325,
    "Ulvl_Scaled": 0.38,
    "NumAgglos": 249,
    "NumAgglos_Scaled": 0.215,
    "Mpop": 0.538,
    "ADBC": 32.6,
    "ADBC_Scaled": 0.158,
    "Usurf": 0.0062,
    "Country_FR": "Tanzanie",
    "name": "Dodoma",
    "Tpop": 48861166,
    "X2": "Capital: Dodoma",
    "Surface": "Population: 48 786 000",
    "description": "Tanzania is the second most populous country in East Africa after Ethiopia. It stands out amongst most African countries in that it possesses a system of territorial administration that recognizes urban, rural and “mixed” wards, integrating the reality of zones that are between the urban-rural spectrum. These mixed wards do not simply serve the purpose of classification, instead they are deliberate, organized and managed in a way that recognizes future demographic growth. As the population increases or densifies, wards are either reclassified or sub-divided to create new ones.\nThis managed approach to urbanization is also reflected in the evolution of the country’s urban agglomerations, which are planned to anticipate growth and eventually transform from small to medium and from medium to large agglomerations. Dar es Salam stands out as the largest urban agglomeration with 5.3 million inhabitants in 2015, Tanzania counts four other agglomerations with more than 500 000 inhabitants (Arusha, Mwanza, Zanzibar and Mbeya). However, smaller urban agglomerations (10 000 – 50 000 inhabitants) are growing fast and account for about a quarter of the urban population.\nOverall, the country has seen one of the most rapid increase in its urban population on the continent. Between 1957 and 2015, Arusha’s population increased 88-fold, that of Mbeya grew 73-fold and the capital Dodoma saw its population multiply by 21. In the 5 years since 2010 alone, Dar es Salam has seen its surface area triple and its population increase by 30% as a result of its merger with four smaller agglomerations."
  },
  {
    "Country": "Uganda",
    "ISO": "UGA",
    "ID": 46,
    "Upop": 14041116,
    "Upop_Scaled": 0.286,
    "Ulvl_Scaled": 0.39,
    "NumAgglos": 124,
    "NumAgglos_Scaled": 0.107,
    "Mpop": 0.547,
    "ADBC": 6.5,
    "ADBC_Scaled": 0.032,
    "Usurf": 0.0226,
    "Country_FR": "Ouganda",
    "name": "Kampala",
    "Tpop": 36002862,
    "X2": "Capital: Kampala",
    "Surface": "Population: 35 551 000",
    "description": "In 1980, Uganda was one of the least urbanized countries in the world. It has since undergone a remarkable transformation. In the five years since 2010, Uganda’s level of urbanization more than doubled from 18.3% to 39.5% in 2015. At the same time, the primacy of the capital Kampala has been practically decimated: in 2010, Kampala was still 16 times larger than the second biggest agglomeration but by 2015, it was barely twice as populous as the second-ranking agglomeration Mbale.\nKampala still accounts for more than a quarter of the total urban population, but medium-sized agglomerations are increasingly important in terms of the urban population distribution. In 2015, they accounted for 41% of the total urban population. Nonetheless, more than half of all agglomerations in Uganda (83 out of 125) are smaller ones with populations between 10 000 and 50 000 inhabitants.\nThis growth in urbanization is largely driven by the increasing density of rural areas (i.e. in-situ urbanization), with many agglomerations having sprung up around the major road networks. Some extend in linear form and merge with other smaller agglomerations. These newer agglomerations are generally characterized by a relatively low population density and many lack a distinctly urban character. At 3 015 inhabitants per km2, Uganda has the seventh lowest average urban population density in Africa.\nAmongst the largest agglomerations are a few whose urban network expands beyond the border. This is the case for the agglomerations of Mbale and Busia, which extend into Kenya, and Kabale on the Rwandan border. The southern part of the country has seen the biggest growth in urban population. At the current pace, the area around Lake Victoria could see the emergence of a megapolis with more than 10 million people in the coming decades."
  },
  {
    "Country": "South Africa",
    "ISO": "ZAF",
    "ID": 47,
    "Upop": 38177616,
    "Upop_Scaled": 0.492,
    "Ulvl_Scaled": 0.7,
    "NumAgglos": 500,
    "NumAgglos_Scaled": 0.432,
    "Mpop": 0.526,
    "ADBC": 16.8,
    "ADBC_Scaled": 0.082,
    "Usurf": 0.0101,
    "Country_FR": "Afrique du Sud",
    "name": "Pretoria",
    "Tpop": 54539451,
    "X2": "Capital: Pretoria",
    "Surface": "Population: 54 647 000",
    "description": "At 70%, the Republic of South Africa has the highest level of urbanization in Africa. Africapolis counts a total of 502 urban agglomerations in South Africa – the third highest figure in Africa. In 2015, almost half of all urban dwellers lived in cities with more than 500 000 inhabitants. The agglomeration of Johannesburg, which includes Pretoria, the Witwatersrand, Soshanguwe and multiple smaller agglomerations, accounts for 8.3 million inhabitants, representing a fifth of the total urban population of South Africa.\nThe average urban population density however is relatively low at 3 102, which is related to the relatively vast spread of some urban agglomerations. Historically, many of the early cities of South Africa have been designed as “garden cities”, i.e. cities with a lot of open green spaces. These cities’ built environment is relatively spread out, intercut with areas without any construction. Given the morphological approach of Africapolis, this means that some cities appear as multiple agglomerations in the Africapolis database.\nMajor changes in the pattern of urbanization become visible after 1990, i.e. during the end of Apartheid. Between 1990 and 2000, the number of urban agglomerations increases from 171 to 462, with much of that growth stemming from smaller agglomerations with fewer than 50 000 inhabitants. The urban population grows at a rate of 5.4% (compared to 2.9% during the previous decade) whereas the rural population starts to experience a decline, a trend that continued until 2015."
  },
  {
    "Country": "Democratic Republic of Congo",
    "ISO": "COD",
    "ID": 48,
    "Upop": 31206400,
    "Upop_Scaled": 0.433,
    "Ulvl_Scaled": 0.44,
    "NumAgglos": 496,
    "NumAgglos_Scaled": 0.428,
    "Mpop": 0.506,
    "ADBC": 34.2,
    "ADBC_Scaled": 0.166,
    "Usurf": 0.0018,
    "Country_FR": "République démocratique du Congo",
    "name": "Kinshasa",
    "Tpop": 70923636,
    "X2": "Capital: Kinshasa",
    "Surface": "Population: 71 246 000",
    "description": "The Democratic Republic of Congo is the most populous country in Central Africa and the fourth most populous in Africa. It is also the largest country in terms of surface area in Sub-Saharan Africa. In 2015, it reached an urbanization level of 44% and counted a total of 496 urban agglomerations.\nThe network of urban agglomerations is relatively vast and balanced across the territory. The capital Kinshasa is the largest urban agglomeration with an estimated population of 7.3 million. It has the highest density of any capital in Sub-Saharan Africa with an average of 16 924 inhabitants per km2. The population density of Kinshasa and its weight in the total urban population also explain the relatively high average urban population density of the country, which stood at 7 495 inhabitants per km2 – the second highest in Africa behind Ivory Coast.\nD. R. Congo’s urban population has increased rapidly in the past 20 years. It more than doubled from 13.9 million in 2000 to 31.2 million in 2015. There has also been a strong growth in the number of smaller agglomerations with fewer than 50 000 inhabitants over the same period. In 2015, these smaller agglomerations accounted for almost a third of the total urban population, but four-fifths were not recognized by any national or international statistic. Most smaller agglomerations seem to have sprung up along the network of improvised dirt tracks that pervade Congo’s territory. They are also the result of people seeking out denser settlements in a climate of insecurity. In fact, isolated villages and towns remain rare in D. R. Congo except for the North-East."
  },
  {
    "Country": "Zambia",
    "ISO": "ZMB",
    "ID": 49,
    "Upop": 6819645,
    "Upop_Scaled": 0.225,
    "Ulvl_Scaled": 0.44,
    "NumAgglos": 75,
    "NumAgglos_Scaled": 0.065,
    "Mpop": 0.52,
    "ADBC": 53.2,
    "ADBC_Scaled": 0.259,
    "Usurf": 0.0029,
    "Country_FR": "Zambie",
    "name": "Lusaka",
    "Tpop": 15499193,
    "X2": "Capital: Lusaka",
    "Surface": "Population: 15 474 000",
    "description": "Zambia is a sparsely populated country with an average of 21 inhabitants per km2. Unlike most other African countries, Zambia’s urban profile is characterized by a marked absence of smaller agglomerations. The capital Lusaka holds more than a third of all urban dwellers and is six times larger than the second biggest city Kitwe.\nThe stretch of land that forms the North-Western border with DR Congo - known as the Copperbelt - has been the location of several larger agglomerations, such as Chingola, Kitwe and Ndola, whose existence is linked to copper mining. However, the fluctuations in copper prices have meant that many of these are in decline. This stands in contrast with the growth of medium-sized urban agglomerations (between 50 000 and 500 000 inhabitants) whose population has increased from 1.6 million in 2000 to 2.1 million in 2015.\nA feature of Zambia’s urbanization is the existence of spontaneous settlements on the periphery of cities that are unrecognized in the official statistics. As a result, the official urbanization statistics divert largely from the findings of Africapolis. Since only the populations living within the official boundaries of cities are captured, the official statistics underestimate the true extent of urbanization and, in some cases, ignore entire urban agglomerations that have sprung up spontaneously through the merger of smaller localities without any attachment to an official city. This is for instance the case of several agglomerations along the Eastern side of Lake Mweru in Northern Zambia. Some of these agglomerations, like Mwatishi and Nchelenge, stretch out over a length of more than 20km, occasionally reaching population densities above 3 000 inhabitants per km2."
  },
  {
    "Country": "Zimbabwe",
    "ISO": "ZWE",
    "ID": 50,
    "Upop": 4800985,
    "Upop_Scaled": 0.208,
    "Ulvl_Scaled": 0.34,
    "NumAgglos": 53,
    "NumAgglos_Scaled": 0.046,
    "Mpop": 0.612,
    "ADBC": 23.7,
    "ADBC_Scaled": 0.115,
    "Usurf": 0.0038,
    "Country_FR": "Zimbabwe",
    "name": "Harare",
    "Tpop": 14120544,
    "X2": "Capital: Harare",
    "Surface": "Population: 13 943 000",
    "description": "Zimbabwe’s level of urbanization has only progressed slowly and is one of the lowest in Africa at 33%. The urban landscape is dominated by Harare and the second agglomeration Bulawayo. Together, they account for almost two-thirds of the urban population in 2015. Harare is however more than 3 times larger than Bulawayo and its primacy is expected to increase further over the next years.\nThe average urban population density is relatively low level at only 3 322 inhabitants per km2. Most urban agglomerations are spread out as planning policies have encouraged the construction of various blocs of settlements that are not linked by any built environment. As a result, the Africapolis database registers many more agglomerations (53 in total) than are officially recognized, as some cities become subdivided into separate agglomerations.\nA striking feature of Zimbabwe is the relative low weight of smaller agglomerations overall. They account for only 16% of the urban population and unlike other African countries, Zimbabwe has not seen a significant growth in their number over the past two decades. The spontaneous emergence of agglomerations that has happened in other African nations is rendered almost impossible by the top-down approach in planning and the tight control over land that is exercised by the government.\nOnly the suburbs of Harare and the South-East show some signs of spontaneous settlements. Harare has in fact absorbed other agglomerations, such as Epworth and Chitungwiza, and is increasingly encroaching on the rural wards that surround the capital."
  }
];
