export const WHATSNEW = [
  {
    "ID": 0,
    "whatsNew": 'whatsNew',
    "title": "Africapolis report 2019",
  },
  {
    "ID": 1,
    "whatsNew": 'whatsNew',
    "title": "Africa's largest cities 2019",
  },{
    "ID": 2,
    "whatsNew": 'whatsNew',
    "title": "Madagascar data available",
  }
]

  export const NARRATIVES = [
    {
      "ID": 0,
      "content": 'narrative',
      "content_title": 'What is Africapolis',
      "title": "Africapolis",
      "subtitle": "How the case of Onitsha challenges the rural exodus hypothesis of urbanization in Africa",
      "whatsnew": "What makes us closer",
      "overview": "Over the past 60 years, urbanisation and cities have fundamentally transformed the social, economic and political geography of West Africa. The number of people living in cities increased from 5 million in 1950 to 133 million in 2010. During the same period, the number of towns and cities with more than 10 000 inhabitants grew from 159 to close to 2 000. A large majority of these agglomerations are secondary cities and small towns that act as hubs and catalysts for local and regional production and supply chains, as well as for the transfer of goods, people and information, linking the local and regional economies to the global economy.",
      "story": [
        {
          "storyID": 0,
          "storyTitle": "1. Understanding urbanisation dynamics in Africa",
          "storyText": "Africa is projected to have the fastest urban growth rate in the world - by 2050, Africa’s cities will be home to an additional 950 million people. There is a continuous need to better understand urbanisation, what it looks like today and what this means for the future. "
        },
        {
          "storyID": 1,
          "storyTitle": "2. Africapolis: A unique platform on cities and urbanisation in Africa",
          "storyText": "Africapolis is the only comprehensive and standardised geospatial database on cities and urbanisation dynamics in Africa. It is designed to enable comparative and long-term analyses of urban dynamics - covering 7 500 agglomerations in 50 countries. "
        },
        {
          "storyID": 2,
          "storyTitle": "3. Planning for Africa’s urban future  ",
          "storyText": "Managing urbanisation is one of Africa’s great development challenges. More data and a stronger evidence-base is needed to support cities and governments to make urban areas more inclusive, livable and productive."
        },
      ]
    },
    {
      "ID": 1,
      "content": 'narrative',
      "title": "Defining urban",
      "subtitle": "How the case of Onitsha challenges the rural exodus hypothesis of urbanization in Africa",
      "whatsnew": "Update on the Annual Report 2018",
      "overview": " ",
      "story": [
        {
          "storyID": 0,
          "storyTitle": "From cities to “Urban Agglomerations”",
          "storyText": "Africapolis takes a spatial approach to understanding urban agglomerations, putting the focus on the built environment as a variable in determiningwhat entities count as urban. The spatial approach stands in stark contrast to the use of national planning documents or statistics in determining the extent of urbanization, the latter relying strongly on the political recognition of cities as administrative and legal units. However, what counts as a “city” is country-specific and may even change over time, making comparisons between countries difficult. The concept of city is in fact a political construct where the boundaries of the city are determined centrally, whereas Africapolis considers the material reality on the ground, thereby highlighting that the boundaries of agglomerations are, in fact, dynamic and fluid. Africapolis defines as urban any agglomeration that includes more than 10,000 inhabitants. By using the lower threshold of 10,000 inhabitants, Africapolis shows that smaller agglomerations make up an important part of urban settlements in Africa. Compared to the World Urbanization Prospects (WUP) database, which only takes into account agglomerations with more than 300,000 inhabitants, Africapolis reveals 25 times as many urban agglomerations – a total of around 7,400. From a methodological perspective, this approach allows us to make comparisons within and between countries and regions much more easily. "
        },
        {
          "storyID": 1,
          "storyTitle": "Onitsha, Nigeria: A case of in-situ urbanization",
          "storyText": "By focusing on agglomerations rather than cities, Africapolis reveals trends that challenge some of the common perceptions about urbanization, such as the concept of rural exodus as a driver of urbanization. Taking the specific example of Onitsha in Nigeria, Africapolis data shows that the idea of rural immigration driving the growth of agglomerations is inadequate in explaining the emergence of Onitsha, which today represents one of the largest urban agglomerations in West Africa. The town of Ontisha itself, is located in the North-Western corner of the agglomeration and has been recognized as a market town since the 1950s. It is made up of three different local government authorities (LGAs), one of which is Onitsha proper, and counts 176,000 inhabitants on an area of just 28 km2. By contrast, the agglomeration of Onitsha had a population of 8.5 million people in 2015, spread out on an area 100 times as large as Ontisha itself and with a density just short of 3000 inhabitants per km2. Onitsha today ranks as the second largest agglomeration in Nigeria behind Lagos. It is expected to reach a population of 25 million by 2050 and could eventually merge with Aba, Uyo and Port Harcourt, forming a much larger agglomeration that would outstrip Lagos and Kano in both size and population. Despite its size and the potential policy and planning implications this involves, Ontisha does not figure anywhere in the literature or in planning, policy and statistical analyses. Besides Onitsha, Africa is home to several such large spontaneous agglomerations that Africapolis refers to as “unidentified geographical objects” since their urban character and morphology are not recognized by the national institutions. The spatial dimension is crucial in understanding how these agglomerations came into existence. Onitsha, for instance, has not grown through the influx of rural populations but instead is an example of in-situ urbanization: the agglomeration has grown organically through the increasing population density in existing settlements that have grown and merged into one bigger agglomeration once the density has reached a certain critical mass. Not only do these spontaneous agglomerations not result from an influx of rural populations, they emerge in fact from the opposite: the absence of emigration from rural areas, which fuels the increasing population density that eventually leads to the fusion of multiple settlements into a bigger whole. "
        },
        {
          "storyID": 2,
          "storyTitle": "Economically connected but politically unrecognized",
          "storyText": "To understand modern urbanization in Africa, one has to examine the characteristics of the large agglomerations such as the ones in Nigeria’s South-East. Unlike a traditional city, the Onitsha agglomeration has no city center. Instead, it has multiple centers that each engage in their own economic activity, including industry, manufacturing and crafts. Some of the agglomerations of Nigeria are very strongly connected to the global market, not least because the Niger delta is a key production area for natural gas and petroleum. The agglomeration of Aba, wedged between the Ontisha and Uyo agglomerations, is known for its multiple industrial zones that produce anything from textiles to plastics, cosmetics, pharmaceutical products and palm oil. The Ariaria Market is now the largest markets in West Africa, exporting textiles and shoes into the wider world. Finding a proper definition for these agglomerations is not an easy task: they could be qualified as “conurbations” since they do not have one, but multiple centers and agricultural activities tend to co-exist alongside industrial ones. However, the traditional definition of conurbations – which was popularized during the early 20th century to describe the hastily emerging cities built on industrial activity - implies a movement of rural populations towards these industrial areas, which is not the case for Onitsha, Uyo, Aba and Nsukka in Nigeria. Instead, some of these areas are in fact marked by a strong outward flow of people. This is particularly true of Nigeria’s Ibo people that are increasingly migrating towards other areas in the country and outside. Unlike the modern melting pots of the developed world, the agglomerations of South-Eastern Nigeria experience a reduction of social and ethnic diversity as a result of emigration. Ethno-linguistic factors could also explain why, despite their economic weight, the agglomerations of Nigeria’s Niger delta go politically unrecognized. The two main cities of the country, Lagos and Kano, are strongly related to two ethno-linguistic groups: the Yoruba and Haussa respectively. There may be some reluctance in acknowledging the existence of a third center of power controlled predominantly by the Ibo."
        },
        {
          "storyID": 3,
          "storyTitle": "Policy implications",
          "storyText": "The case of Onitsha highlights the limitations of the traditional classification of settlements as “urban” or “cities”. These categories are highly political and therefore inadequate descriptors of the urban reality of modern-day Africa. The focus on larger cities has also resulted in skewing the perception of African urbanization. If we are to better understand and predict future trends in urbanization, it is important to take into account the smaller agglomerations, which – as the case of South-Eastern Nigeria has shown – are likely to predict the emergence of future agglomerations through the fusion of several smaller agglomerations into one. This is particularly true of the African highlands, where population densities are high and the space is limited by political and natural boundaries. For researchers, social scientists and policy-makers, the Africapolis methodology – with its focus on the spatial dimension – could provide important new insight to better manage and predict the growth of Africa’s urban agglomerations. In-situ urbanization is likely to be the biggest factor in the increasing level of urbanization that the continent will see in the next few decades. Only if this trend is properly understood, can policy-makers, urban planners and local governments make adequate decisions about the provision of basic infrastructure and services, and harness the economic potential that emerges from these vibrant places."
        }
      ]
    },
    {
      "ID": 2,
      "content": 'narrative',
      "title": "Going beyond megacities",
      "subtitle": "How the case of Onitsha challenges the rural exodus hypothesis of urbanization in Africa",
      "whatsnew": "Hello World",
      "overview": " ",
      "story": [
        {
          "storyID": 0,
          "storyTitle": "Story 2-1",
          "storyText": "Africapolis takes a spatial approach to understanding urban agglomerations, putting the focus on the built environment as a variable in determining what entities count as urban. The spatial approach stands in stark contrast to the use of national planning documents or statistics in determining the extent of urbanization, the latter relying strongly on the political recognition of cities as administrative and legal units. However, what counts as a “city” is country-specific and may even change over time, making comparisons between countries difficult. The concept of city is in fact a political construct where the boundaries of the city are determined centrally, whereas Africapolis considers the material reality on the ground, thereby highlighting that the boundaries of agglomerations are, in fact, dynamic and fluid. Africapolis defines as urban any agglomeration that includes more than 10,000 inhabitants. By using the lower threshold of 10,000 inhabitants, Africapolis shows that smaller agglomerations make up an important part of urban settlements in Africa. Compared to the World Urbanization Prospects (WUP) database, which only takes into account agglomerations with more than 300,000 inhabitants, Africapolis reveals 25 times as many urban agglomerations – a total of around 7,400. From a methodological perspective, this approach allows us to make comparisons within and between countries and regions much more easily. "
        },
        {
          "storyID": 1,
          "storyTitle": "Story 2-2",
          "storyText": "By focusing on agglomerations rather than cities, Africapolis reveals trends that challenge some of the common perceptions about urbanization, such as the concept of rural exodus as a driver of urbanization. Taking the specific example of Onitsha in Nigeria, Africapolis data shows that the idea of rural immigration driving the growth of agglomerations is inadequate in explaining the emergence of Onitsha, which today represents one of the largest urban agglomerations in West Africa. The town of Ontisha itself, is located in the North-Western corner of the agglomeration and has been recognized as a market town since the 1950s. It is made up of three different local government authorities (LGAs), one of which is Onitsha proper, and counts 176,000 inhabitants on an area of just 28 km2. By contrast, the agglomeration of Onitsha had a population of 8.5 million people in 2015, spread out on an area 100 times as large as Ontisha itself and with a density just short of 3000 inhabitants per km2. Onitsha today ranks as the second largest agglomeration in Nigeria behind Lagos. It is expected to reach a population of 25 million by 2050 and could eventually merge with Aba, Uyo and Port Harcourt, forming a much larger agglomeration that would outstrip Lagos and Kano in both size and population. Despite its size and the potential policy and planning implications this involves, Ontisha does not figure anywhere in the literature or in planning, policy and statistical analyses. Besides Onitsha, Africa is home to several such large spontaneous agglomerations that Africapolis refers to as “unidentified geographical objects” since their urban character and morphology are not recognized by the national institutions. The spatial dimension is crucial in understanding how these agglomerations came into existence. Onitsha, for instance, has not grown through the influx of rural populations but instead is an example of in-situ urbanization: the agglomeration has grown organically through the increasing population density in existing settlements that have grown and merged into one bigger agglomeration once the density has reached a certain critical mass. Not only do these spontaneous agglomerations not result from an influx of rural populations, they emerge in fact from the opposite: the absence of emigration from rural areas, which fuels the increasing population density that eventually leads to the fusion of multiple settlements into a bigger whole. "
        },
        {
          "storyID": 2,
          "storyTitle": "Economically connected but politically unrecognized",
          "storyText": "To understand modern urbanization in Africa, one has to examine the characteristics of the large agglomerations such as the ones in Nigeria’s South-East. Unlike a traditional city, the Onitsha agglomeration has no city center. Instead, it has multiple centers that each engage in their own economic activity, including industry, manufacturing and crafts. Some of the agglomerations of Nigeria are very strongly connected to the global market, not least because the Niger delta is a key production area for natural gas and petroleum. The agglomeration of Aba, wedged between the Ontisha and Uyo agglomerations, is known for its multiple industrial zones that produce anything from textiles to plastics, cosmetics, pharmaceutical products and palm oil. The Ariaria Market is now the largest markets in West Africa, exporting textiles and shoes into the wider world. Finding a proper definition for these agglomerations is not an easy task: they could be qualified as “conurbations” since they do not have one, but multiple centers and agricultural activities tend to co-exist alongside industrial ones. However, the traditional definition of conurbations – which was popularized during the early 20th century to describe the hastily emerging cities built on industrial activity - implies a movement of rural populations towards these industrial areas, which is not the case for Onitsha, Uyo, Aba and Nsukka in Nigeria. Instead, some of these areas are in fact marked by a strong outward flow of people. This is particularly true of Nigeria’s Ibo people that are increasingly migrating towards other areas in the country and outside. Unlike the modern melting pots of the developed world, the agglomerations of South-Eastern Nigeria experience a reduction of social and ethnic diversity as a result of emigration. Ethno-linguistic factors could also explain why, despite their economic weight, the agglomerations of Nigeria’s Niger delta go politically unrecognized. The two main cities of the country, Lagos and Kano, are strongly related to two ethno-linguistic groups: the Yoruba and Haussa respectively. There may be some reluctance in acknowledging the existence of a third center of power controlled predominantly by the Ibo."
        },
        {
          "storyID": 3,
          "storyTitle": "Policy implications",
          "storyText": "The case of Onitsha highlights the limitations of the traditional classification of settlements as “urban” or “cities”. These categories are highly political and therefore inadequate descriptors of the urban reality of modern-day Africa. The focus on larger cities has also resulted in skewing the perception of African urbanization. If we are to better understand and predict future trends in urbanization, it is important to take into account the smaller agglomerations, which – as the case of South-Eastern Nigeria has shown – are likely to predict the emergence of future agglomerations through the fusion of several smaller agglomerations into one. This is particularly true of the African highlands, where population densities are high and the space is limited by political and natural boundaries. For researchers, social scientists and policy-makers, the Africapolis methodology – with its focus on the spatial dimension – could provide important new insight to better manage and predict the growth of Africa’s urban agglomerations. In-situ urbanization is likely to be the biggest factor in the increasing level of urbanization that the continent will see in the next few decades. Only if this trend is properly understood, can policy-makers, urban planners and local governments make adequate decisions about the provision of basic infrastructure and services, and harness the economic potential that emerges from these vibrant places."
        }
      ]
    },
    {
      "ID": 3,
      "content": 'narrative',
      "title": "Analysing urban trends",
      "subtitle": "How the case of Onitsha challenges the rural exodus hypothesis of urbanization in Africa",
      "whatsnew": "Malawi Research",
      "overview": " ",
      "story": [
        {
          "storyID": 0,
          "storyTitle": "Story 3-1",
          "storyText": "Africapolis takes a spatial approach to understanding urban agglomerations, putting the focus on the built environment as a variable in determining what entities count as urban. The spatial approach stands in stark contrast to the use of national planning documents or statistics in determining the extent of urbanization, the latter relying strongly on the political recognition of cities as administrative and legal units. However, what counts as a “city” is country-specific and may even change over time, making comparisons between countries difficult. The concept of city is in fact a political construct where the boundaries of the city are determined centrally, whereas Africapolis considers the material reality on the ground, thereby highlighting that the boundaries of agglomerations are, in fact, dynamic and fluid. Africapolis defines as urban any agglomeration that includes more than 10,000 inhabitants. By using the lower threshold of 10,000 inhabitants, Africapolis shows that smaller agglomerations make up an important part of urban settlements in Africa. Compared to the World Urbanization Prospects (WUP) database, which only takes into account agglomerations with more than 300,000 inhabitants, Africapolis reveals 25 times as many urban agglomerations – a total of around 7,400. From a methodological perspective, this approach allows us to make comparisons within and between countries and regions much more easily. "
        },
        {
          "storyID": 1,
          "storyTitle": "Story 3-2",
          "storyText": "By focusing on agglomerations rather than cities, Africapolis reveals trends that challenge some of the common perceptions about urbanization, such as the concept of rural exodus as a driver of urbanization. Taking the specific example of Onitsha in Nigeria, Africapolis data shows that the idea of rural immigration driving the growth of agglomerations is inadequate in explaining the emergence of Onitsha, which today represents one of the largest urban agglomerations in West Africa. The town of Ontisha itself, is located in the North-Western corner of the agglomeration and has been recognized as a market town since the 1950s. It is made up of three different local government authorities (LGAs), one of which is Onitsha proper, and counts 176,000 inhabitants on an area of just 28 km2. By contrast, the agglomeration of Onitsha had a population of 8.5 million people in 2015, spread out on an area 100 times as large as Ontisha itself and with a density just short of 3000 inhabitants per km2. Onitsha today ranks as the second largest agglomeration in Nigeria behind Lagos. It is expected to reach a population of 25 million by 2050 and could eventually merge with Aba, Uyo and Port Harcourt, forming a much larger agglomeration that would outstrip Lagos and Kano in both size and population. Despite its size and the potential policy and planning implications this involves, Ontisha does not figure anywhere in the literature or in planning, policy and statistical analyses. Besides Onitsha, Africa is home to several such large spontaneous agglomerations that Africapolis refers to as “unidentified geographical objects” since their urban character and morphology are not recognized by the national institutions. The spatial dimension is crucial in understanding how these agglomerations came into existence. Onitsha, for instance, has not grown through the influx of rural populations but instead is an example of in-situ urbanization: the agglomeration has grown organically through the increasing population density in existing settlements that have grown and merged into one bigger agglomeration once the density has reached a certain critical mass. Not only do these spontaneous agglomerations not result from an influx of rural populations, they emerge in fact from the opposite: the absence of emigration from rural areas, which fuels the increasing population density that eventually leads to the fusion of multiple settlements into a bigger whole. "
        },
        {
          "storyID": 2,
          "storyTitle": "Economically connected but politically unrecognized",
          "storyText": "To understand modern urbanization in Africa, one has to examine the characteristics of the large agglomerations such as the ones in Nigeria’s South-East. Unlike a traditional city, the Onitsha agglomeration has no city center. Instead, it has multiple centers that each engage in their own economic activity, including industry, manufacturing and crafts. Some of the agglomerations of Nigeria are very strongly connected to the global market, not least because the Niger delta is a key production area for natural gas and petroleum. The agglomeration of Aba, wedged between the Ontisha and Uyo agglomerations, is known for its multiple industrial zones that produce anything from textiles to plastics, cosmetics, pharmaceutical products and palm oil. The Ariaria Market is now the largest markets in West Africa, exporting textiles and shoes into the wider world. Finding a proper definition for these agglomerations is not an easy task: they could be qualified as “conurbations” since they do not have one, but multiple centers and agricultural activities tend to co-exist alongside industrial ones. However, the traditional definition of conurbations – which was popularized during the early 20th century to describe the hastily emerging cities built on industrial activity - implies a movement of rural populations towards these industrial areas, which is not the case for Onitsha, Uyo, Aba and Nsukka in Nigeria. Instead, some of these areas are in fact marked by a strong outward flow of people. This is particularly true of Nigeria’s Ibo people that are increasingly migrating towards other areas in the country and outside. Unlike the modern melting pots of the developed world, the agglomerations of South-Eastern Nigeria experience a reduction of social and ethnic diversity as a result of emigration. Ethno-linguistic factors could also explain why, despite their economic weight, the agglomerations of Nigeria’s Niger delta go politically unrecognized. The two main cities of the country, Lagos and Kano, are strongly related to two ethno-linguistic groups: the Yoruba and Haussa respectively. There may be some reluctance in acknowledging the existence of a third center of power controlled predominantly by the Ibo."
        },
        {
          "storyID": 3,
          "storyTitle": "Policy implications",
          "storyText": "The case of Onitsha highlights the limitations of the traditional classification of settlements as “urban” or “cities”. These categories are highly political and therefore inadequate descriptors of the urban reality of modern-day Africa. The focus on larger cities has also resulted in skewing the perception of African urbanization. If we are to better understand and predict future trends in urbanization, it is important to take into account the smaller agglomerations, which – as the case of South-Eastern Nigeria has shown – are likely to predict the emergence of future agglomerations through the fusion of several smaller agglomerations into one. This is particularly true of the African highlands, where population densities are high and the space is limited by political and natural boundaries. For researchers, social scientists and policy-makers, the Africapolis methodology – with its focus on the spatial dimension – could provide important new insight to better manage and predict the growth of Africa’s urban agglomerations. In-situ urbanization is likely to be the biggest factor in the increasing level of urbanization that the continent will see in the next few decades. Only if this trend is properly understood, can policy-makers, urban planners and local governments make adequate decisions about the provision of basic infrastructure and services, and harness the economic potential that emerges from these vibrant places."
        }
      ]
    },
  ];


  